#Кузнечная печь

burnTime: 500 #время сгорания 1 единицы топлива в печи
minBurnTemp: 40 #минимальная температура печи при горении
CoolingTime: 500 #время остывания печи

#Форма слитка

MoldcoolingTime: 500 #Время остывание слитка

#Меха

maxTemp: 150 #Максимальная температура до которой можно разогреть печь
