name: RPG-Professions
version: 1.0.0
main: org.owleebr.professions.Main
api-version: 1.21
authors: [OwleeBr]
description: "Плагин работы с профессиями"
#depend: [ProtocolLib]


commands:
    cinv:
        description: Открывает CINV
        usage: /cinv
    getforceps:
        description: Выдает щипцы
        usage: /getforceps
    gethammer:
        description: Выдает молот
        usage: /gethammer

permissions:
  rpg.profession.set:
    description: "Allows setting professions"
    default: op